# Generated by Django 3.0.9 on 2020-08-04 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200804_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='daily_work_hours',
            field=models.PositiveSmallIntegerField(default=8),
            preserve_default=False,
        ),
    ]
