# Generated by Django 3.1 on 2020-08-05 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20200805_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='daily_work_hours',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
